---
development:
  cloud_name: hzkbrr1wv
  api_key: '828968714155541'
  api_secret: pN_v1XUKMUxZc193bbkqfxmCzdg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hzkbrr1wv
  api_key: '828968714155541'
  api_secret: pN_v1XUKMUxZc193bbkqfxmCzdg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hzkbrr1wv
  api_key: '828968714155541'
  api_secret: pN_v1XUKMUxZc193bbkqfxmCzdg
  enhance_image_tag: true
  static_image_support: false
